### ISSUE TITLE
Game Testing Questionnaire 

### ISSUE THREAD

**Issue by johnydorman** [UoSGamesGroups/first-semester-l4-5-group-16#31]
Research and make a questionnaire for game testers.
3 Hours.

**Comment by RobertoMitrea** [comment]
[Game Questionnaire.docx](https://github.com/UoSGamesGroups/first-semester-l4-5-group-16/files/622699/Game.Questionnaire.docx)
Do you think you can change the hours assigned? It took me like 5 hours to do the research and make the questionnaire. Thank you.
